- name: play1
  hosts: all
  vars: 
    URL: play.google.com
  tasks:
    - name: Printing Variable
      ansible.builtin.debug:
        msg: "Value of the url is {{URL}}"
        
    - name: Printing Variable2
      ansible.builtin.debug:
        msg: "Value of the url is {{URL}}"
      vars:
        URL: task.google.com