- name: Demo on facts
  hosts: all
  gather_facts: False
  tasks:
    - name: Printing a fact 
      ansible.builtin.shell: ps -ef|grep java|grep -v grep
      ignore_errors: True

    - name: Printing a fact 
      ansible.builtin.debug: 
        msg: "this is task2, task1 failed"