- name: Demo on tags
  hosts: all
  gather_facts: False
  tasks:
    - name: Installing frontend
      ansible.builtin.debug: 
        msg: Installing frontend
      tags: frontend

    - name: Installing backend
      ansible.builtin.debug: 
        msg: Installing backend
      tags: backend

    - name: Installing mysql
      ansible.builtin.debug: 
        msg: Installing mysql
      tags: mysql

    - name: starting mysql
      ansible.builtin.debug: 
        msg: starting mysql
      tags: mysql