- name: Demo on Package
  hosts: all
  gather_facts: False
  become: true
  tasks:
    - name: UNInstalling nginx
      ansible.builtin.package: 
        name: nginx
        state: absent

    - name: UNInstalling nginx
      ansible.builtin.package: 
        name: nginx
        state: present